[package]
name = "ics_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icalendar = "0.15.8"
chrono-tz = "0.8.4"
chrono = "0.4"